name: "Jesse Raab"
title: "Jesse Raab"
email: "jesse.r.raab@gmail.com"
markdown: redcarpet
pygments: True
redcarpet:
   extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables', 'with_toc_data'] 
